### PR TITLE
fix ambiguous cats instances

### LINKED ISSUE #75: Ambiguos implicits with Cats instances
New bug introduced by #70 , I will have a look this evening. 

Some instances that use subtyping create ambiguity, e.g. `Hash` extends `Eq`.

### PR DESCRIPTION
**Pull request by gvolpe**
fixes #75

Added a bunch of tests so next time should be more difficult to break it :)

### CODE REVIEW

**Comment by gvolpe** [comment]
@Iltotore further thoughts on this. Right now we need these imports to have instances and syntax in scope:

```scala
import io.github.iltotore.iron.cats.{ given, * }
```

What do you think about having something like this instead?

```scala
import io.github.iltotore.iron.cats.given
import io.github.iltotore.iron.cats.syntax.*
```

This is Scala 3 being at fault IMO. I would take a `*` import to mean *everything*, including typeclass instances.

File: cats/src/io/github/iltotore/iron/cats.scala [hunk 1]
```diff
@@ -93,3 +91,6 @@ private object IronCatsInstances:
   inline given [A, B](using inline ev: Semilattice[A]): Semilattice[A :| B] = ev.asInstanceOf[Semilattice[A :| B]]
   inline given [A, B](using inline ev: Show[A]): Show[A :| B] = ev.asInstanceOf[Show[A :| B]]
   inline given [A, B](using inline ev: UpperBounded[A]): UpperBounded[A :| B] = ev.asInstanceOf[UpperBounded[A :| B]]
+
+private trait IronCatsLowPriority0:
```
Comment (Iltotore) [inline cats/src/io/github/iltotore/iron/cats.scala:95]: Why a `0` in the name? It does not seem necessary since we only have a single trait

**Review by Iltotore — APPROVED** [review]
